# Generated by Django 4.0 on 2021-12-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.URLField(default=''),
        ),
    ]
