# Generated by Django 4.0 on 2021-12-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_education_skills_workexperience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
